from math import floor, factorial, sqrt

# Using floor on everthing with a / to remove the .0 on the end of it
print('Nul', 4 - 4 - 4 + 4)
print('Een', floor(4 / 4 * 4 / 4))
print('Twee', floor(4 / 4 + 4 / 4))
print('Drie', floor((4 + 4 + 4) / 4))
print('Vier', factorial(4) - (4 * 4) - 4)
print('Vijf', floor((4 * 4 + 4) / 4))
print('Zes', floor((4 + 4) / 4 + 4))
print('Zeven', floor(44 / 4 - 4))
print('Acht', floor(4 + 4 * 4 / 4))
print('Negen', floor(4 + 4 + 4 / 4))
print('Tien', floor((44 - 4) / 4))
print('Elf', floor(44 / (sqrt(4) + sqrt(4))))
print('Twaalf', floor(4 * (4 - 4 / 4)))
print('Dertien', floor(factorial(4) - 44 / 4))
print('Viertien', 4 + 4 + 4 + sqrt(4))
print('Vijftien', floor(4 * 4 - 4 / 4))
print('Zestien', floor(4 * 4 * (4 / 4)))
print('Zeventien', floor(4 * 4 + 4 / 4))
print('Achtien', floor(4 * 4 + 4 / sqrt(4)))
print('Negentien', floor(factorial(4) - 4 - 4 / 4))
print('Twintig', floor(4 * ((4 / 4) + 4)))
